### PR TITLE
fix all bogs of schema pages

### PR DESCRIPTION
**Pull request by farzad2919**
change 'json prettify' font size
change class of buttons
fix bogs of pages
fix job problem of 'department' part in "local business" page
Note 1. to see changes of 'json perttify' style must restart terminal
Note 2. i dont see any problem with number of lines in' json prettify' component
Note 3. only bog is in 'oppening time' part in local business

### CODE REVIEW

**Comment by farzad2919** [comment]
fix all warnings

**Review by Xaankoo-Noyan — CHANGES_REQUESTED** [review]
According to the feedback in our [private chat](https://chat.google.com/dm/p95XnUAAAAE/gIImdLcqOcs/gIImdLcqOcs?cls=10), make sure everything are working well.

**Comment by farzad2919** [comment]
fix bog of Condition in product page

**Review by babak-x — APPROVED** [review]
Finally, the request gets merged.

**Review by Xaankoo-Noyan — APPROVED** [review]

**Pull request merged**
